name: Feature suggestion
description: Suggest a feature or enhancement to be added to Blockaid
labels: suggestion
body:
- type: checkboxes
  attributes:
    label: Checklist
    description: Perform these required steps before filling out a feature suggestion.
    options:
      - label: I have checked **[both open and closed issues](https://github.com/PrecisionRender/Blockaid/issues?q=is%3Aissue)** to ensure this is the first instance of this feature being suggested.
        required: true
      - label: I am using the **latest release** version of Blockaid.
        required: true
      - label: I am not using a **custom build** or **fork** of Blockaid.
        required: true
      - label: I am sure that this a **feature suggestion**, not a bug.
        required: true
      - label: I believe this feature will improve the usability and efficiency of the purpose of Blockaid.
        required: true

- type: textarea
  attributes:
    label: Feature description
    description: Please describe your suggestion in detail. Feel free to include mockups, example code, or anything else you think will help you describe your suggestion.
  validations:
    required: true

- type: textarea
  attributes:
    label: Why this feature benefits Blockaid
    description: |
      Please describe why and how you think this feature would benefit Blockaid, and explain any problems it tries to solve.
      Explain how the user experience of Blockaid would be improved, and if you think the program is comparatively incomplete without the feature or not. 
      Remember, Blockaid maintains a focus on simplicity and intuitivity. Features that are obscure or overly confusing are not in harmony with this focus.
  validations:
    required: true
